### ISSUE TITLE
`read ECONNRESET` error

### ISSUE THREAD

**Issue by creeperyang** [mklabs/tiny-lr#104]
Sometimes got error:

```bash
#  node@6.2.1

Error: read ECONNRESET
      at exports._errnoException (util.js:1007:11)
      at TCP.onread (net.js:563:26)
```

livereload/LiveReload#12 has a detailed discussion

**Comment by mklabs** [comment]
Hi @creeperyang Thanks for the PR! and thanks @hemanth for the merge!
