### ISSUE TITLE
Investigate "handle socket error to prevent possible app crash, such as ECONNRESET"

### ISSUE THREAD

**Issue by mklabs** [mklabs/tiny-lr#113]
See if we should rollback this commit to limit the described behavior in 

https://github.com/mklabs/tiny-lr/commit/303f95c6f5b309eaf608c50a070537809d9c0ba7#commitcomment-19591161

**Comment by creeperyang** [comment]
@matthewmueller I confirm that the error is caught by my pr.

However, different versions of node has different behavior about `Error: read ECONNRESET` (an error occured when client abruptly closed the connection of TCP.)

When I push the code, my console sometimes output the message:

```bash
Error: read ECONNRESET
    at exports._errnoException (util.js)
    at TCP.onread (net.js)
```

It's annoying and you can't control it. (Um, maybe you can listen  to `uncaughtexception`).

I tested on node@6.9.0, the `ECONNRESET` seems be dropped defaultly?


By the way, maybe you can ignore it by filter the error with:

```
if (error.code !== 'ECONNRESET') { console.log(error) }
```

because the error is like 

```bash
{ Error: read ECONNRESET
       at exports._errnoException (util.js:1026:11)
       at TCP.onread (net.js:569:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } }
```

**Comment by creeperyang** [comment]
I don't think this will lead to tons of the error. When I test, one tab of chrome only lead to one error.

**Comment by mklabs** [comment]
Thanks @creeperyang for detailed explanation.

I need to test it further, but maybe we can silent out `ECONNRESET` type of errors

**Comment by creeperyang** [comment]
@mklabs yeah, you're right. It seems inevitable in our case.

**Comment by matthewmueller** [comment]
fwiw, this isn't an issue at all if i downgrade to `"tiny-lr": "0.2.1"`

**Comment by aknuds1** [comment]
I keep getting this error, Node 6.9.1.

**Comment by matthewmueller** [comment]
Could be wrong, but ignoring the error seems like a bandaid. If this error was inevitable, wouldn't it affect all websocket servers?

**Comment by asgoth** [comment]
Don't know if it is related, but with version 1.0.2 I sometimes get:

    console - ... Uhoh. Got error undefined ...

Don't seem to get it with version 1.0.3 (for now). I was trying to check if something was changed in 1.0.3 which could explain it.

Only noticed a bug in one of the latest pr's: https://github.com/mklabs/tiny-lr/pull/114/files#diff-c945a46d13b34fcaff544d966cffcabaR157

[Function apply](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply) expects an array, not an Error object (function call a comma separated list)

**Comment by creeperyang** [comment]
@asgoth yeah, a silly mistake.
