### ISSUE TITLE
Printing error message throws an exception.

### ISSUE THREAD

**Issue by cv711** [mklabs/tiny-lr#120]
Transient crash, it happened after a manual refresh.

project/node_modules/tiny-lr/src/server.js:266
      console.error('... Uhoh. Got error %s ...', e.message);
                                                   ^

TypeError: Cannot read property 'message' of undefined
    at Server.error (/project/node_modules/tiny-lr/src/server.js:266:52)
    at Socket.<anonymous> (/project/node_modules/tiny-lr/src/server.js:217:22)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:319:10)
    at onwrite (_stream_writable.js:337:5)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at fireErrorCallbacks (net.js:462:13)
    at Socket._destroy (net.js:503:3)
    at WriteWrap.afterWrite (net.js:795:10)

**Comment by mklabs** [comment]
Hi,

Thanks for the feedback. May I ask you how do you use tiny-lr ? Do you use it directly, or with a build tool like gulp or grunt ? With which gulp or grunt plugin ? Is it with express as a middleware etc. ? 

Also, which version of tiny-lr are you running ? Just for me to be able to reproduce if I can.

**Comment by LokeshPatel** [comment]
Hi,
I have getting same error message after install ionic 2 and run ionic serve command on window 7 system.
After enable "cross origin resource sharing" option in chrome working fine.

**Comment by cybentizen** [comment]
Hi @LokeshPatel,

How did you enable the "cross origin resource sharing" option in chrome? Can you please help?

**Comment by frederikbosch** [comment]
Also having this issue. Latest version, using it Broccoli.

**Comment by frederikbosch** [comment]
Added a PR.

**Comment by speedfl** [comment]
+1 :)
